package UppercaseModule;


/**
* UppercaseModule/UppercaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UpperModule.idl
* Friday, April 25, 2025 3:22:04 PM IST
*/

public interface UppercaseOperations 
{
  String to_uppercase (String str);
} // interface UppercaseOperations
