package UppercaseModule;


/**
* UppercaseModule/UppercasePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UpperModule.idl
* Friday, April 25, 2025 3:22:04 PM IST
*/

public abstract class UppercasePOA extends org.omg.PortableServer.Servant
 implements UppercaseModule.UppercaseOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("to_uppercase", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // UppercaseModule/Uppercase/to_uppercase
       {
         String str = in.read_string ();
         String $result = null;
         $result = this.to_uppercase (str);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:UppercaseModule/Uppercase:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Uppercase _this() 
  {
    return UppercaseHelper.narrow(
    super._this_object());
  }

  public Uppercase _this(org.omg.CORBA.ORB orb) 
  {
    return UppercaseHelper.narrow(
    super._this_object(orb));
  }


} // class UppercasePOA
